name: Github Beta commit to telegram

on:
  push:
    branches:
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 此步骤使用 GitHub 的 https://github.com/actions/checkout
    - name: checkout actions
      uses: actions/checkout@v1

    # 设置python环境
    # 此步骤使用 GitHub 的 https://github.com/actions/setup-python
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    # 安装依赖
    - name: Install dependencies
      run: |
        mkdir tmp && cd tmp
        python -m pip install --upgrade pip
        pip install requests
    # 发送通知
    - name: Send notice
      run: |
        cd tmp
        cp ../telegram_update_beta.py ./
        python telegram_update_beta.py ${{ secrets.TG_BOT_TOKEN }}